### ISSUE TITLE
Consider converting the viperHTML account into an organisation

### ISSUE THREAD

**Issue by ExE-Boss** [viperHTML/viperhtml.github.io#18]
Since the @viperHTML account serves only to host the https://viperhtml.js.org website, it might be a good idea to [convert it to a GitHub organisation](https://help.github.com/articles/converting-a-user-into-an-organization/) with the owner being set to @WebReflection.

Among the advantages to doing this is that you’ll be able to manage it as an administrator without needing to log into the @viperHTML account and you’ll get an organisation landing page like @mozilla, @mozilla-mobile, @mdn, @NOVA-Team and @OpenCDM (I wanted to go with @OpenDRM, but someone has already taken that).

**Comment by WebReflection** [comment]
done
