### ISSUE TITLE
Left navigation extends over content on hyperHTML doc page

### ISSUE THREAD

**Issue by grommett** [viperHTML/viperhtml.github.io#2]
After scrolling down the documentation page and then refreshing, the left navigation extends over the content. Resizing the window after this happens resolves the issue.

**System**:
- Mac OS 10.12.6
- Chrome 60.0.3112.90

**Steps to repeat**:
1. Go to hyperHTML [documentation page](https://viperhtml.js.org/hyperhtml/documentation/)
1. Scroll down some (how far is irrelevant)
1. Refresh page

**Result**:

Left navigation extends into the content area.
![image](https://user-images.githubusercontent.com/141877/29253419-bfd1b67c-807c-11e7-8f2b-63e70516df1e.png)

**Comment by WebReflection** [comment]
it should be fine now, thanks.
