### ISSUE TITLE
Add lighterHTML

### ISSUE THREAD

**Issue by ExE-Boss** [viperHTML/viperhtml.github.io#32]
See&nbsp;[@WebReflection/lighterHTML](https://github.com/WebReflection/lighterHTML)

**Comment by WebReflection** [comment]
already in the README https://github.com/WebReflection/hyperHTML#lighterhtml-

not sure I want to add it before it reaches v1.0

there are also plans to ship `lighterssr` at some point, and both cases might have their own dedicated website.
